### ISSUE TITLE
Should we use the sumologic image?

### ISSUE THREAD

**Issue by fernando-alves** [techops-peopledata/fluentd#12]
As there's no active development here, maybe we should just use the image folks on Sumologic are maintaining.

**Comment by Stono** [comment]
I think thats wise - @stevezau added some separation in as well, if you get stuck when we come to look at this - reach out to him :)

**Comment by fernando-alves** [comment]
Just FYI, we did it :P

**Comment by Stono** [comment]
Mate, 17 months to do this story.  Pull ya finger out!

**Comment by fernando-alves** [comment]
1 day doing it
509 days trying to exit vim

:P
